// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQuXqo__0zo7n8rn-7ZZVMKY93mDfICXE',
    appId: '1:860847177242:web:f83ff7d9e7c096757a9ba3',
    messagingSenderId: '860847177242',
    projectId: 'productivity-app-auth-001',
    authDomain: 'productivity-app-auth-001.firebaseapp.com',
    storageBucket: 'productivity-app-auth-001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT1BNGqpHz5LnV7Km9s1WSp1PTYE3ZizY',
    appId: '1:860847177242:android:c71c0e3b70d2fccc7a9ba3',
    messagingSenderId: '860847177242',
    projectId: 'productivity-app-auth-001',
    storageBucket: 'productivity-app-auth-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi8uDua2LIpPrwRx2fihZsjPErxPVMM-E',
    appId: '1:860847177242:ios:578fc9ba0e55b7fb7a9ba3',
    messagingSenderId: '860847177242',
    projectId: 'productivity-app-auth-001',
    storageBucket: 'productivity-app-auth-001.firebasestorage.app',
    iosBundleId: 'com.example.productivityAppV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi8uDua2LIpPrwRx2fihZsjPErxPVMM-E',
    appId: '1:860847177242:ios:578fc9ba0e55b7fb7a9ba3',
    messagingSenderId: '860847177242',
    projectId: 'productivity-app-auth-001',
    storageBucket: 'productivity-app-auth-001.firebasestorage.app',
    iosBundleId: 'com.example.productivityAppV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQuXqo__0zo7n8rn-7ZZVMKY93mDfICXE',
    appId: '1:860847177242:web:e1204900a8216e257a9ba3',
    messagingSenderId: '860847177242',
    projectId: 'productivity-app-auth-001',
    authDomain: 'productivity-app-auth-001.firebaseapp.com',
    storageBucket: 'productivity-app-auth-001.firebasestorage.app',
  );
}
